dist: bionic
language: python
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
  - pip2 install -r requirements-python2.txt
  - pip3 install nose
# command to run tests
script:
  - nosetests